"""Create and adopt the PostgreSQL application schema.

This revision is intentionally safe to run against the short-lived PostgreSQL
schema created by the former compatibility layer: it only creates missing
objects or columns, converts ISO timestamp columns, and drops the obsolete
version marker. It never drops application data.
"""

from alembic import op

revision = "20260820_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    CREATE TABLE IF NOT EXISTS runs (
      id TEXT PRIMARY KEY,
      status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'done', 'error')),
      progress DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
      message TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '',
      params_json TEXT NOT NULL DEFAULT '{}',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(), started_at TIMESTAMPTZ,
      finished_at TIMESTAMPTZ, worker_id TEXT, attempt_count INTEGER NOT NULL DEFAULT 0,
      heartbeat_at TIMESTAMPTZ, duration_seconds INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS contratos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      run_id TEXT REFERENCES runs(id) ON DELETE CASCADE, numero_controle TEXT,
      orgao_cnpj TEXT, orgao_nome TEXT, uf TEXT, municipio TEXT, ano TEXT,
      sequencial TEXT, objeto TEXT, valor TEXT, data_publicacao TEXT,
      status TEXT NOT NULL DEFAULT 'final', motivo_status TEXT NOT NULL DEFAULT '',
      item_url TEXT NOT NULL DEFAULT '', UNIQUE (run_id, numero_controle)
    );
    CREATE TABLE IF NOT EXISTS participantes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      contrato_id BIGINT NOT NULL REFERENCES contratos(id) ON DELETE CASCADE,
      cnpj TEXT NOT NULL, nome TEXT, papel TEXT NOT NULL, valor_homologado DOUBLE PRECISION,
      situacao_cadastral TEXT NOT NULL DEFAULT '', UNIQUE (contrato_id, cnpj)
    );
    CREATE TABLE IF NOT EXISTS cnpjs_auditoria (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
      contrato_id BIGINT NOT NULL REFERENCES contratos(id) ON DELETE CASCADE,
      cnpj TEXT NOT NULL, nome TEXT NOT NULL DEFAULT '', source TEXT NOT NULL,
      disposition TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '', origin_file TEXT NOT NULL DEFAULT '',
      situacao_cadastral TEXT NOT NULL DEFAULT '', UNIQUE (run_id, contrato_id, cnpj, disposition)
    );
    CREATE TABLE IF NOT EXISTS cnpj_evidencias (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
      contrato_id BIGINT NOT NULL REFERENCES contratos(id) ON DELETE CASCADE,
      cnpj TEXT NOT NULL, origin_file TEXT NOT NULL, scan_pass TEXT NOT NULL,
      page_number INTEGER NOT NULL DEFAULT 0, category TEXT NOT NULL, signal TEXT NOT NULL DEFAULT '', excerpt TEXT NOT NULL DEFAULT ''
    );
    CREATE TABLE IF NOT EXISTS metricas_funil (
      contrato_id BIGINT PRIMARY KEY REFERENCES contratos(id) ON DELETE CASCADE,
      run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
      atas_lidas INTEGER NOT NULL DEFAULT 0, atas_falhas INTEGER NOT NULL DEFAULT 0,
      cnpjs_ata_unicos INTEGER NOT NULL DEFAULT 0, removido_invalido INTEGER NOT NULL DEFAULT 0,
      removido_orgao INTEGER NOT NULL DEFAULT 0, removido_vencedor INTEGER NOT NULL DEFAULT 0,
      candidatos_inconclusivos INTEGER NOT NULL DEFAULT 0, perdedores_final INTEGER NOT NULL DEFAULT 0,
      vencedores INTEGER NOT NULL DEFAULT 0, vencedores_inferidos INTEGER NOT NULL DEFAULT 0,
      resultado_final INTEGER NOT NULL DEFAULT 0, documentos_listados INTEGER NOT NULL DEFAULT 0,
      documentos_prioritarios_lidos INTEGER NOT NULL DEFAULT 0, documentos_fallback_lidos INTEGER NOT NULL DEFAULT 0,
      documentos_ignorados INTEGER NOT NULL DEFAULT 0, documentos_duplicados INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS perfis_busca (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT NOT NULL UNIQUE,
      termos_json TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS documentos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
      contrato_id BIGINT REFERENCES contratos(id) ON DELETE CASCADE,
      source_url TEXT NOT NULL, s3_bucket TEXT, s3_key TEXT, sha256 TEXT,
      size_bytes BIGINT, content_type TEXT, downloaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      status TEXT NOT NULL DEFAULT 'downloaded', UNIQUE (run_id, source_url)
    );
    """)
    for table, column, definition in (
        ("runs", "duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
        ("runs", "worker_id", "TEXT"),
        ("runs", "attempt_count", "INTEGER NOT NULL DEFAULT 0"),
        ("runs", "heartbeat_at", "TIMESTAMPTZ"),
        ("participantes", "situacao_cadastral", "TEXT NOT NULL DEFAULT ''"),
        ("cnpjs_auditoria", "situacao_cadastral", "TEXT NOT NULL DEFAULT ''"),
        ("metricas_funil", "candidatos_inconclusivos", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "documentos_listados", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "documentos_prioritarios_lidos", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "documentos_fallback_lidos", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "documentos_ignorados", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "documentos_duplicados", "INTEGER NOT NULL DEFAULT 0"),
        ("metricas_funil", "vencedores_inferidos", "INTEGER NOT NULL DEFAULT 0"),
    ):
        op.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
    op.execute("""
    DO $$
    DECLARE column_name text;
    BEGIN
      FOREACH column_name IN ARRAY ARRAY['created_at', 'started_at', 'finished_at', 'heartbeat_at'] LOOP
        IF EXISTS (
          SELECT 1 FROM information_schema.columns AS columns_info
          WHERE columns_info.table_schema = current_schema() AND columns_info.table_name = 'runs'
            AND columns_info.column_name = column_name AND columns_info.data_type IN ('text', 'character varying')
        ) THEN
          EXECUTE format(
            'ALTER TABLE runs ALTER COLUMN %I TYPE timestamptz USING NULLIF(%I::text, '''')::timestamptz',
            column_name, column_name
          );
        END IF;
      END LOOP;
      IF EXISTS (
        SELECT 1 FROM information_schema.columns AS columns_info
        WHERE columns_info.table_schema = current_schema() AND columns_info.table_name = 'perfis_busca'
          AND columns_info.column_name = 'created_at' AND columns_info.data_type IN ('text', 'character varying')
      ) THEN
        ALTER TABLE perfis_busca ALTER COLUMN created_at TYPE timestamptz
          USING NULLIF(created_at::text, '')::timestamptz;
      END IF;
    END $$;
    """)
    op.execute("""
      CREATE INDEX IF NOT EXISTS idx_contratos_uf ON contratos(uf);
      CREATE INDEX IF NOT EXISTS idx_contratos_run ON contratos(run_id);
      CREATE INDEX IF NOT EXISTS idx_auditoria_run_disposition ON cnpjs_auditoria(run_id, disposition);
      CREATE INDEX IF NOT EXISTS idx_evidencias_run_cnpj ON cnpj_evidencias(run_id, cnpj);
      CREATE INDEX IF NOT EXISTS idx_runs_status_created ON runs(status, created_at, id);
      CREATE INDEX IF NOT EXISTS idx_documentos_run ON documentos(run_id);
    """)
    # The old runtime used this table instead of Alembic. It carries no domain data.
    op.execute("DROP TABLE IF EXISTS schema_version")


def downgrade():
    # Deliberately non-destructive: production rollback must retain analysis data.
    pass
